# Generated by Django 3.2.8 on 2021-12-10 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('data', models.FloatField()),
                ('collection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='countyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('countyfp', models.IntegerField(blank=True, null=True, unique=True)),
                ('countyns', models.CharField(blank=True, max_length=8, null=True)),
                ('geoid', models.CharField(blank=True, max_length=55555, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=100, null=True)),
                ('lsad', models.CharField(blank=True, max_length=2, null=True)),
                ('classfp', models.CharField(blank=True, max_length=2, null=True)),
                ('mtfcc', models.CharField(blank=True, max_length=5, null=True)),
                ('csafp', models.CharField(blank=True, max_length=3, null=True)),
                ('cbsafp', models.CharField(blank=True, max_length=5, null=True)),
                ('metdivfp', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat', models.CharField(blank=True, max_length=1, null=True)),
                ('aland', models.BigIntegerField()),
                ('awater', models.BigIntegerField()),
                ('intptlat', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=12, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='exampleDataNokey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('fips', models.CharField(max_length=5)),
                ('countyseat', models.CharField(max_length=100)),
                ('est', models.FloatField()),
                ('origin', models.CharField(max_length=500)),
                ('etymology', models.CharField(max_length=500)),
                ('population', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='mapMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapname', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=40, null=True)),
                ('dateadded', models.DateField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mapGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyname', models.CharField(max_length=100)),
                ('fips', models.CharField(max_length=5)),
                ('floatdata', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('mapname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.mapmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='mapControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('mapname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.mapmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='exampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('fips', models.CharField(max_length=5)),
                ('countyseat', models.CharField(max_length=100)),
                ('est', models.FloatField()),
                ('origin', models.CharField(max_length=500)),
                ('etymology', models.CharField(max_length=500)),
                ('population', models.FloatField()),
                ('countymap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.countymap')),
            ],
        ),
    ]
