# Generated by Django 3.2.8 on 2021-12-13 02:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontrol',
            name='upper_limit',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapcontrol',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=None),
        ),
    ]
