# Generated by Django 3.2.8 on 2021-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_auto_20211213_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapgeometry',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
