# Generated by Django 3.2.8 on 2021-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0003_alter_mapgeometry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapgeometry',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
