# Generated by Django 3.2.8 on 2022-01-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0007_alter_mapmetadata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='countymap',
            name='offsetx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countymap',
            name='offsety',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mapgeometry',
            name='offsetx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mapgeometry',
            name='offsety',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mapmetadata',
            name='declutter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statetiger',
            name='offsetx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statetiger',
            name='offsety',
            field=models.FloatField(default=0),
        ),
    ]
