# Generated by Django 3.2.8 on 2022-01-20 06:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0009_mapmetadata_make_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='font_size',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='mapmetadata',
            name='line_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='mapmetadata',
            name='line_weight',
            field=models.IntegerField(default=3),
        ),
    ]
