# Generated by Django 3.2.8 on 2022-01-20 06:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0010_auto_20220120_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='font_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='mapmetadata',
            name='font_inlay_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=None),
        ),
    ]
