# Generated by Django 3.2.8 on 2022-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0011_auto_20220120_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='font_inlay_weight',
            field=models.IntegerField(default=3),
        ),
    ]
