# Generated by Django 3.2.8 on 2022-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0012_mapmetadata_font_inlay_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='show_osm',
            field=models.BooleanField(default=True),
        ),
    ]
