# Generated by Django 3.2.8 on 2022-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0013_mapmetadata_show_osm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='lonlat',
            field=models.CharField(default='-88.528,39.938', max_length=500),
        ),
        migrations.AddField(
            model_name='mapmetadata',
            name='zoom',
            field=models.FloatField(default=6),
        ),
    ]
