# Generated by Django 3.2.8 on 2022-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0014_auto_20220120_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmetadata',
            name='toggle_value_display',
            field=models.BooleanField(default=True),
        ),
    ]
